import "./globals.css";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="tr">
            <body>
                <div className="fixed h-screen w-full bg-gradient-to-br from-indigo-100 via-white to-cyan-200" />
                {/* nav */}
                <main className="flex min-h-screen w-full flex-col items-center justify-center py-32">
                    {children}
                </main>
                {/* footer */}
                {/* analytics */}
            </body>
        </html>
    );
}
