import NavBar from "components/layout/NavBar";
import Footer from "components/layout/Footer";
import "./globals.css";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="tr">
            <body>
                <div className="h-full w-full bg-gradient-to-br from-indigo-100 via-white to-cyan-200">
                    <NavBar />
                    <main className="flex min-h-screen w-full flex-col items-center justify-center py-32">
                        {children}
                    </main>
                    <Footer />
                    {/* analytics */}
                </div>
            </body>
        </html>
    );
}
